app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import flash, jsonify, render_template, redirect, request, url_for

from app.models import Claim, Service, User
from . import home as home_blueprint
from app.forms import AddUser
from app import database
from datetime import datetime
import datetime as dt


@home_blueprint.route('/all/users', methods=['GET'])
def all_users():
    """
    List all Users
    """
    all_users = User.query.all()
    return render_template('home/home.html', users=all_users, title="Users")

@home_blueprint.route('/user/<int:id>', methods=['GET', 'POST'])
def view_user(id):
    """
        A route that allows claim officer fillout a form for a particular user
    """
    user_data = User.query.get(int(id))
    return render_template('home/user_data.html', user_data=user_data)

@home_blueprint.route('/user/<int:id>/edit', methods=['GET', 'POST'])
def edit_user(id):
    """
        A route for editing a user record
    """
    form = AddUser()

    user_data = User.query.get(int(id))

    if request.method == 'POST':
        name = request.form.get('name')
        gender = request.form.get('gender')
        salary = request.form.get('salary')
        date_of_birth = request.form.get('date_of_birth')

        dt_obj = datetime.strptime(date_of_birth, '%Y-%m-%d')

        if form.validate_on_submit():
            user_data.name = name
            user_data.gender = gender
            user_data.salary = salary
            user_data.date_of_birth = dt_obj

            database.session.commit()

            flash('User updated successfully.', 'success')
            return redirect(url_for('home.edit_user', id=user_data.id))

    return render_template('home/edit_user.html', user_data=user_data, form=form)

@home_blueprint.route('users/add', methods=['GET', 'POST'])
def add_user():
    """
        A route for adding users

    """
    form = AddUser()

    if request.method == 'POST':
        name = request.form.get('name')
        gender = request.form.get('gender')
        salary = request.form.get('salary')
        date_of_birth = request.form.get('date_of_birth')

        dt_obj = datetime.strptime(date_of_birth, '%Y-%m-%d')

        if form.validate_on_submit():
            new_user = User(name=name, gender=gender, salary=salary, date_of_birth=dt_obj)
            database.session.add(new_user)
            database.session.commit()

            flash('User created successfully.', 'success')
            return redirect(url_for('home.all_users'))

        flash('You entered and invalid form data', 'danger')
        return render_template('home/create_user.html', form=form)
    else:
        
        return render_template('home/create_user.html', form=form)

@home_blueprint.route('/user/<int:id>/delete', methods=['POST'])
def delete_user(id):
    """
        A route for deleting a user
    """
    user_data = User.query.get(int(id))
    database.session.delete(user_data)
    database.session.commit()

    flash('User deleted successfully.', 'success')
    return redirect(url_for('home.all_users'))


@home_blueprint.route('claim', methods=['GET'])
def claim():
    """
    List all Claims
    """
    all_claims = Claim.query.all()
    return render_template('home/claim.html', claims=all_claims, title="Claims")

@home_blueprint.route('create_claim', methods=['GET', 'POST'])
def create_claim():
    """
        A route for a claim officer to make/create a claim
    """

    if request.method == 'POST':
        # Get the form field values for claim model insertion

        user = request.form.get('user')
        diagnosis = request.form.get('diagnosis')
        hmo = request.form.get('hmo')

        total_cost = request.form.get('total_cost')
        service_charge = request.form.get('service_charge')
        final_cost = request.form.get('final_cost')

        user = User.query.filter_by(name=user).first()
        new_claim = Claim(user_id=user.id, diagnosis=diagnosis, hmo=hmo, service_charge=service_charge,total_cost=total_cost, final_cost=final_cost)
        database.session.add(new_claim)
        database.session.commit()

        # Get the form field values for service model insertion
        service_name = request.form.getlist('service_name')
        service_type = request.form.getlist('type')
        provider_name = request.form.getlist('provider_name')
        source = request.form.getlist('source')
        cost_of_service = request.form.getlist('cost_of_service')

        dates = request.form.getlist('service_date')

        # Formate dates
        service_date = []
        for d in dates:
            service_date.append(datetime.strptime(d, '%Y-%m-%d'))
        print("Anthony", service_date)

        # Get the above claim as foreign key for services
        claim = Claim.query.filter().last()

        # Loop to enter possible list of services
        for i in range(len(service_name)):
            new_service = Service(claim_id=claim.id, service_date=service_date[i], service_name=service_name[i], type=service_type[i], provider_name=provider_name[i], source=source[i], cost_of_service=cost_of_service[i])
            database.session.add(new_service)
            database.session.commit()

        flash('Claim created successfully.', 'success')
        return redirect(url_for('home.claim'))
    else:
        all_users = User.query.with_entities(User.name).all()
        return render_template('home/create_claim.html', all_users=all_users)

@home_blueprint.route('create_claim/age/', methods=['POST'])
def user_age():
    """
        A route to get a user's birthdate
        and calculate his age 
    """
    if request.method == "POST":
        data = request.form.get("age").strip()
        user = User.query.filter_by(name=data).first()
        age = (dt.date.today().year - user.date_of_birth.year)
        print(age)
 
    
    return jsonify({'age': age})

app/templates/home/base.html
<!DOCTYPE html>
<html>
<head>
  <title>Intron</title>
  <!-- icon -->
	<link rel="shortcut icon" href="../static/images/favicon-pos.png"  type="images/customer-logo-8" >
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  
  <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">

  <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet" />


</head>

<body>
  
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-main">
          <span class="sr-only">Toggle</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="" class="navbar-brand">
          <img src="" class="img-responsive" alt="Logo">
        </a>
      </div>
      <div class="collapse navbar-collapse" id="navbar-collapse-main">
        <ul class="nav navbar-nav navbar-right">
          <li> <a href="{{url_for('home.all_users')}}"> Home </a> </li>
          <li> <a href="{{url_for('home.add_user')}}"> Add User </a> </li>
          <li> <a href="{{url_for('home.claim')}}"> Claims </a> </li>
          <li> <a href="{{url_for('home.create_claim')}}"> Create Claim </a> </li>
          <li><a href="#footer">Support</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container main">

    <!-- Flash messages -->

    <div>
      {% with messages = get_flashed_messages(with_categories = true) %}
        {% if messages %}
            {% for category,  message in messages %}
                <div class="alert alert-{{ category }} flash" role=alert> 
                    {{ message }} 
                    <button class="close" data-dismiss="alert">
                        <span aria-hidden="true" > &times; </span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
      {% endwith %}
    </div>

    {% block body %} 

    {% endblock %}
  </div>

  <footer id="footer" class="container-fluid text-center footer navbar-fixed-bottom">
 
    <p class="copyright">
      Copyright &copy; 2021 - Powered by <a href="https://intron.io/" target="_blank"> Intron Health</a>
    </p>
  </footer>        
  
  <script type="application/javascript">
    $(document).ready(function(){
        var path = window.location.pathname.split("/").pop();
        if (path == ''){
            path = 'index';
        }

        // var target = $('ul li a[href="'+path+'"]');
        var target = $("a[href$='"+path+"']");
        target.addClass('active');
    });
  </script>

  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script> -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

  <script type="application/javascript">
    
    $(document).ready(function () {
        $('#userTable').DataTable();
        $('.dataTables_length').addClass('bs-select');
    });

</script>

</body>
</html>

app/templates/home/claim.html
{% extends "home/base.html" %}

{% block title %} All Users {% endblock %}

{% block body %}
<div class="panel-list">
    <h3 class="ml-2 mt-3 text-center">All Claims</h3>
    <div class="row row-content">

        <div class="table-responsive-sm col-12">
            {% if claims|length > 0 %}
                <table class="table table-sm table-panel table-desktop" id="userTable">
                    <thead class="">
                        <tr>
                            <th scope="col th-sm">S/N</th>
                            <th scope="col th-sm">Name</th>
                            <th scope="col th-sm">Salary</th>
                            <th scope="col th-sm">Date Joined</th>
                            <th scope="col th-sm">Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for claim in claims %}
  
                        {% endfor %}
                    </tbody>
                </table>

            {% else %}
                <div class="text-center empty-table" style="display: block;">No Claims to display</div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

app/templates/home/create_claim.html
{% extends "home/base.html" %}

{% block title %} User{% endblock %}

{% block body %}
<div class="user user-claim">
    <h2 class="text-center">Create Claim</h2>
    <form class="form-group claim-form" action="" method="POST">

            <div class="col">
                <div class="row">
                    <div class="col-sm-4">
                        <label for="user-claim">User</label>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <select name="user" id="user-claim"  class="form-control">
                                <option value="">Select User</option>
                                {% for data in all_users %}
                                    <option value="{{ data[0] }}">{{ data[0] }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <label for="user-claim">Diagnosis</label>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <textarea name="diagnosis" id=""  class="form-control" placeholder="Diagnosis" required></textarea>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <label for="user-claim">HMO</label>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <select name="hmo" id="user-claim"  class="form-control" required>
                                <option value="">Select HMO</option>                        
                                <option value="HMO1">HMO1</option>
                                <option value="HMO2">HMO2</option>
                                <option value="HMO3">HMO3</option>
                                <option value="HMO4">HMO4</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <label for="user-age">Age</label>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <input type="number" id="user-age" name="age" class="form-control" placeholder="Age" min="0" value="" required readonly>
                        </div>
                    </div>
                </div>

                <div class="row text-center" id="service-section">
                    <h3> Service Section</h3>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <label for="">Service Date</label>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <input type="date" name="service_date" class="form-control" placeholder="Service Date" required>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <label for="service_name">Service Name</label>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <input type="text" name="service_name" class="form-control" placeholder="Service Name" required>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <label for="type">Service Type</label>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <input type="radio" id="type" name="type" value="Hematology">
                            <label for="vehicle1"> Hematology</label><br>
                            <input type="radio" id="type" name="type" value="Microbiology">
                            <label for="vehicle2">Microbiology</label><br>
                            <input type="radio" id="type" name="type" value="Chemical Pathology">
                            <label for="vehicle3">Chemical Pathology</label><br>
                            <input type="radio" id="type" name="type" value="Histopathology">
                            <label for="vehicle3">Histopathology</label><br>
                            <input type="radio" id="type" name="type" value="Immunology">
                            <label for="vehicle3">Immunology</label><br>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <label for="provider_name">Provider Name</label>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <input type="text" name="provider_name" class="form-control" placeholder="Provider Name" required>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <label for="source">Source</label>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <input type="text" name="source" class="form-control" placeholder="Source" required>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <label for="cost_of_service">Cost of Service</label>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <input type="text" id="cost-of-service" name="cost_of_service" class="form-control services" placeholder="Cost of Service" onkeyup="claim()" required>
                        </div>
                    </div>
                </div>

                <hr>

                <div class="row" id="service-div">
                    <div class="form-group">
                        <input type="button" class="btn btn-primary" id="add-service" value="Add Another Service">
                    </div>
                </div>

                <div class="row text-center" id="service-section">
                    <h3> Total</h3>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <label for="total-cost">Total Cost</label>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <input type="text" id="total-cost" name="total_cost" class="form-control" placeholder="Total Cost"required readonly>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <label for="service-charge">Service Charge</label>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <input type="text" id="service-charge" name="service_charge" class="form-control" placeholder="Service Charge"required readonly>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <label for="final-cost">Final Cost</label>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <input type="text" id="final-cost" name="final_cost" class="form-control" placeholder="Final Cost"required readonly>
                        </div>
                    </div>
                </div>

                     
                <input type="submit" class="btn btn-success" value="Create Claim"> 
                      
            </div>
            
    </form>
</div>

<script src="{{ url_for('static', filename='js/claim.js') }}"></script>
{% endblock %}

app/templates/home/create_user.html
{% extends "home/base.html" %}

{% block title %} User{% endblock %}

{% block body %}
    <div class="form">
        <h2 class="text-center">Create User</h2>
        <form class="form-group" action="" method="POST">

                {{ form.hidden_tag() }}
                <div class="col">
                        <div class="row">
                            <div class="col-sm-5">
                                {{ form.name.label }}:
                            </div>
                            <div class="col-sm-7">
                                {{ form.name( class='form-control') }}
                                {% for error in form.name.errors %}
                                    <span style="color: red;">[{{ error }}]</span>
                                {% endfor %}
                            </div>
                        </div> 
                        <div class="row">
                            <div class="col-sm-5">
                                {{ form.gender.label }}:
                            </div>
                            <div class="col-sm-7">
                                {% for subfield in form.gender %}
                                    <tr>
                                        <td>{{ subfield }}</td>
                                        <td>{{ subfield.label }}</td>
                                    </tr>
                                {% endfor %}
                                {% for error in form.gender.errors %}
                                    <span style="color: red;">[{{ error }}]</span>
                                {% endfor %}
                            </div>
                        </div> 
                        <div class="row">
                            <div class="col-sm-5">
                                {{ form.salary.label }}:
                            </div>
                            <div class="col-sm-7">
                                {{ form.salary(class='form-control') }}
                                {% for error in form.salary.errors %}
                                    <span style="color: red;">[{{ error }}]</span>
                                {% endfor %}
                            </div>
                        </div> 
                        <div class="row">
                            <div class="col-sm-5">
                                {{ form.date_of_birth.label }}:
                            </div>
                            <div class="col-sm-7">
                                {{ form.date_of_birth(class='form-control') }}
                                {% for error in form.date_of_birth.errors %}
                                    <span style="color: red;">[{{ error }}]</span>
                                {% endfor %}
                            </div>
                        </div> 
                        <div class="row text-center">
                            <div class="col-sm-5">

                            </div>
                            <div class="col-sm-7">
                                <input type="submit" class="btn btn-success" value="Add"> 
                            </div>
                        </div>
                </div>
                
        </form>
    </div>
{% endblock %}

app/templates/home/edit_user.html
{% extends "home/base.html" %}

{% block title %} User{% endblock %}

{% block body %}

    <div class="form">
        <h2 class="text-center">Edit User</h2>
        <form class="form-group" action="" method="POST">

            {{ form.hidden_tag() }}
            <div class="col">
                    <div class="row">
                        <div class="col-sm-5">
                            <label for="name">name</label>:
                        </div>
                        <div class="col-sm-7">
                            <input class="form-control" id="name" maxlength="100" minlength="3" name="name" required="" type="text" value="{{user_data.name}}">
                        </div>
                    </div> 
                    <div class="row">
                        <div class="col-sm-5">
                            <label for="gender">gender</label>:
                        </div>
                        <div class="col-sm-7">
                                    <input id="text" name="gender" type="text" value="{{ user_data.gender }}">
                                    <input id="gender-0" name="gender" type="radio" value="male">
                                    <label for="gender-0">male</label>
                                
                                    <input id="gender-1" name="gender" type="radio" value="female">
                                    <label for="gender-1">female</label>
                            
                        </div>
                    </div> 
                    <div class="row">
                        <div class="col-sm-5">
                            <label for="salary">Salary</label>:
                        </div>
                        <div class="col-sm-7">
                            <input class="form-control" id="salary" min="0" name="salary" required="" type="number" value="{{ user_data.salary }}">
                            
                        </div>
                    </div> 
                    <div class="row">
                        <div class="col-sm-5">
                            <label for="date_of_birth">Date Of Birth</label>:
                        </div>
                        <div class="col-sm-7">
                            <input class="form-control" id="date_of_birth" name="date_of_birth" required="" type="date" value="{{user_data.date_of_birth}}">
                            
                        </div>
                    </div> 
                    <div class="row text-center">
                        <div class="col-sm-5">

                        </div>
                        <div class="col-sm-7">
                            <input type="submit" class="btn btn-success" value="Add"> 
                        </div>
                    </div>
            </div>
            
        </form>
    </div>

    <script src="{{ url_for('static', filename='js/edit_user.js') }}"></script>
{% endblock %}

app/templates/home/home.html
{% extends "home/base.html" %}

{% block title %} All Users {% endblock %}

{% block body %}
<div class="panel-list">
    <h3 class="ml-2 mt-3 text-center">All Users</h3>
    <div class="row row-content">
        <div class="col-12">
            <h4>{{ Users }}</h4>
        </div>

        <div class="table-responsive-sm col-12">
            {% if users|length > 0 %}
                <table class="table table-sm table-panel table-desktop" id="userTable">
                    <thead class="">
                        <tr>
                            <th scope="col th-sm">S/N</th>
                            <th scope="col th-sm">Name</th>
                            <th scope="col th-sm">Salary</th>
                            <th scope="col th-sm">Date Joined</th>
                            <th scope="col th-sm">Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for user in users %}
                            <tr class='clickable-row'>
                                <th scope="row">{{ loop.index }}</th>
                                <td>{{ user.name }}</td>
                                <td>{{ user.salary }}</td>
                                <td>{{ user.time_created.strftime('%Y/%m/%d') }}</td>
                                <td>
                                    <a href="{{url_for('home.view_user', id=user.id)}}">
                                        <span class="material-icons outlined"> visibility </span>
                                    </a>
                                    <a href="{{url_for('home.edit_user', id=user.id)}}">
                                        <span class="material-icons outlined"> edit </span>
                                    </a>
                                    <a type="button" data-toggle="modal" data-target="#DeleteModal{{user.id}}">
                                        <span class="material-icons outlined"> delete </span>
                                    </a> 

                                       <!-- Delete Modal -->
                                        <div class="modal" id="DeleteModal{{user.id}}" >
                                            <div class="modal-dialog">
                                                <div class="modal-content">

                                                    <!-- Modal Header -->
                                                    <div class="modal-header">
                                                        <h1 class="modal-title">Delete User</h1>
                                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    </div>

                                                    <!-- Modal body -->
                                                    <div class="modal-body">
                                                        <p>Are you sure you want to delete this User?</h>
                                                    </div>

                                                    <!-- Modal footer -->
                                                    <div class="modal-footer">

                                                        <form action="{{url_for('home.delete_user', id=user.id)}}" method="post">
                                                        
                                                            <div class="content-footer">
                                                                <button class="btn btn-danger deletebtn ">DELETE</button>
                                                            </div>
                                                        </form>

                                                    </div>

                                                </div>
                                            </div>
                                        </div>


                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            {% else %}
                <div class="text-center empty-table" style="display: block;">No Users to display</div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

app/templates/home/user_data.html
{% extends "home/base.html" %}

{% block title %} User{% endblock %}

{% block body %}
    <div class="user">
        <h2>
            {{ user_data.name}}
        </h2>
    </div>
{% endblock %}